buildscript{
    ext.kotlin_version='1.7.1'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
        ///classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}



allprojects {
    repositories {
        google()
        mavenCentral()
    }
    
    // Configure Java toolchain to use Java 17 for compilation (avoids jlink issues)
    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        options.compilerArgs += ['-Xlint:-options']
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                compileSdkVersion 34
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_11
                    targetCompatibility JavaVersion.VERSION_11
                }
            }
        }
        
        // Completely disable androidJdkImage configuration to prevent jlink errors
        project.configurations.all { configuration ->
            if (configuration.name == 'androidJdkImage') {
                configuration.canBeResolved = false
                configuration.canBeConsumed = false
            }
        }
        
        // Disable all jlink-related tasks
        project.tasks.all { task ->
            if (task.name.contains('jlink') || task.name.contains('JdkImage') || task.name.contains('JdkImageTransform')) {
                task.enabled = false
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}


