org.gradle.jvmargs=-Xmx2G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.enableR8.fullMode=false
org.gradle.java.installations.auto-detect=false
android.defaults.buildfeatures.androidResources=true
android.experimental.enableSourceSetPathsMap=false
